name: built_collection
version: 6.0.0-dev
description: >
  Immutable collections based on the SDK collections. Each SDK collection class
  is split into a new immutable collection class and a corresponding mutable
  builder class.
repository: https://github.com/google/built_collection.dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
